### ISSUE TITLE
Can't control since last update

### ISSUE THREAD

**Issue by Bug38** [Robbe-B/maestro_mcz#105]
**Describe the bug**
Since 0.5.1 I can't control the state or the fans

**Expected behavior**
In last versions I was able to turn on/off the stove or it's fans

**Screenshots**
![Screenshot_20240209-195710.jpg](https://github.com/Robbe-B/maestro_mcz/assets/8133398/548412de-a3a0-4f19-a0a6-b7d41b541eeb)

**Comment by Robbe-B** [comment]
Hi @Bug38,

It seems like the stove isn't linked to your mcz account anymore (from what I can see in the screenshot).

-Is the MCZ mobile phone app still working for your stove ?
-Did you tried reloading the integration ? 
-Which home assistant version are you using ?
-What integration version were you using before the upgrade ? 
-Can your roll back to that version to see if it's working again ? 

Kind regards,
Robbe

**Comment by Bug38** [comment]
I can switch eco mode ON/OFF, so I think the connexion is ok.
Maestro app works ok too.
HA Core is the 2023.11.2, it seems it's not the latest I'll try to manually update (android doesn't provide an update)

**Comment by Robbe-B** [comment]
You might wanne upgrade to 2024.2
The 0.5.1 version of this integration uses some specific features introduced in this specific release.

**Comment by Robbe-B** [comment]
Also, if you like the work we do, consider leaving a star on this repo.
Thanks !

Kind regards,
Robbe

**Comment by Bug38** [comment]
After a full night of update for my raspberry, HACore is now in the latest version and my stove is fully functional now 🙂

Thanks for your reactivity !

> Also, if you like the work we do, consider leaving a star on this repo.
Of course !
