### ISSUE TITLE
Climate. entity is missing

### ISSUE THREAD

**Issue by Voidfloop** [Robbe-B/maestro_mcz#106]
After the update to version 0.5.1 the climate. entities are missing.

[0.5.1 config_entry-maestro_mcz-d24d308ef5c23dc50397bbaae35c6e9f.json.txt](https://github.com/Robbe-B/maestro_mcz/files/14298315/0.5.1.config_entry-maestro_mcz-d24d308ef5c23dc50397bbaae35c6e9f.json.txt)

**Comment by Robbe-B** [comment]
@Voidfloop,
I see you don't meet the requirements in order to run v0.5.1

See warning => https://github.com/Robbe-B/maestro_mcz/releases/tag/v0.5.1-beta

You need to have at least HA Core 2024.2 installed.

You are running version: "2024.1.6"

**Comment by Voidfloop** [comment]
Oh crap, I missed it

**Comment by Robbe-B** [comment]
No problem, this can happen to the best 🤣.

Kind regards,
