### ISSUE TITLE
Blank textboxes during setup

### ISSUE THREAD

**Issue by Robbe-B** [Robbe-B/maestro_mcz#11]
Even when my language is set to english. 
During setup, you can have this issue where there is no placeholder text inside the textboxes (makes the user confused about what to write inside these textboxes)
![image](https://user-images.githubusercontent.com/103053873/217031336-cefca2d3-34d5-4e78-a337-32a4ea7d3e6a.png)
![image](https://user-images.githubusercontent.com/103053873/217031398-d85962f8-a418-4776-a9c6-73afaf67843a.png)

**Comment by Robbe-B** [comment]
I'm wondering if this was a HA issue that has been fixed ? 
I'm not able to reproduce this anymore.

**Comment by Crisicus** [comment]
I've only encountered it once very early on in development. I've not seen it since

**Comment by Robbe-B** [comment]
Same, I guess we can conclude this issue is not present anymore, since it's also not that major, I'll close it at this point. Can be re-opened if this would be needed.
