### ISSUE TITLE
Stove is permanently switched on

### ISSUE THREAD

**Issue by Voidfloop** [Robbe-B/maestro_mcz#110]
Both of my stoves are switched "off" but in HA the climate. entity is "on".
I can only click on turn off. The command is also forwarded to the Stove.
If I turn the stove on via the app, the climate. entity switches to "off".

After the switch-on phase, the climate entity switches to switched "on".

What I noticed positively was that if a timer was active, it was switched off.

Both stoves are actually switched off here
![Stove2](https://github.com/Robbe-B/maestro_mcz/assets/146527945/93be45f6-de3e-418e-a59c-c8faf683e5d6)

Here is the logbook after the start phase
![logbuch](https://github.com/Robbe-B/maestro_mcz/assets/146527945/4c00fdaf-d8f2-48d7-9205-b6c331fdf133)

I have no idea if it makes a difference but I have two diagnostic files. Once where the Keller Stove is turned off and once where it is turned on.
[Stove off config_entry-maestro_mcz-e9d62cca0e6589800c92b485d53c8b8e.json](https://github.com/Robbe-B/maestro_mcz/files/14362765/Stove.off.config_entry-maestro_mcz-e9d62cca0e6589800c92b485d53c8b8e.json)
[Stove on config_entry-maestro_mcz-e9d62cca0e6589800c92b485d53c8b8e.json](https://github.com/Robbe-B/maestro_mcz/files/14362768/Stove.on.config_entry-maestro_mcz-e9d62cca0e6589800c92b485d53c8b8e.json)

**Comment by Voidfloop** [comment]
Here is the logbook from the shutdown phase.
the stove is off and the climate. entity remains on.
![Logbuch Stove_Off](https://github.com/Robbe-B/maestro_mcz/assets/146527945/6304b61d-7dd3-4817-aa04-a6d302490024)

**Comment by jmigueloliveira** [comment]
Same problem with my stove

**Comment by Robbe-B** [comment]
@jmigueloliveira,
Are you also able to provide your diagnostics file when the stove is off but reported in HA as on ? 
I already have a fix ready, but this time, I really want to know for sure no side effects will be present for other models.

Kind regards,
Robbe
.

**Comment by jmigueloliveira** [comment]
Hi @Robbe-B !
See attached
![IMG_20240222_064946](https://github.com/Robbe-B/maestro_mcz/assets/148912483/2ce50537-d43c-4747-adb7-233cbf887e87)

**Comment by Voidfloop** [comment]
Great, it works!

Is there actually a function that forces the Stove to send current data?
States are only updated if you manually make a setting for example as turning the timer on or off.
The problem seems to be a general one. Even in the MCZ app, data/status is only updated if you actively make a setting.

**Comment by Robbe-B** [comment]
@Voidfloop, 
The states should be updated every x seconds according to the polling time option (default => every 30sec)
![image](https://github.com/Robbe-B/maestro_mcz/assets/103053873/49899c50-8b34-45ec-8591-35737ee56cf5)

Or shortly after a set.


Yes indeed, the polling is not that great, but due to the backend limitations of MCZ, there is really no way for us to make it faster.
We could try to poll faster with the risk of getting blocked out => thats why you currently can't set the polling time lower than 30sec.
The goal is to mimic the behavior of the MCZ mobile app and polling at a faster rate would put more load on the backend, which we don't want 😄. 
Otherwise we may risk a shutdown of this integration.

Kind regards,
Robbe

**Comment by Voidfloop** [comment]
That's exactly what doesn't seem to work. Maybe the polling time is triggered differently on the older stoves?

**Comment by jmigueloliveira** [comment]
My stove keeps permanently switched on
![IMG_20240222_221134](https://github.com/Robbe-B/maestro_mcz/assets/148912483/ec4b2067-18f3-48a2-97ca-85cda05ce97c)
![Screenshot_2024-02-22-22-04-31-739_io homeassistant companion android](https://github.com/Robbe-B/maestro_mcz/assets/148912483/893cede6-611f-402d-a2ab-00f913354e62)
![Screenshot_2024-02-22-22-04-10-395_it mcz maestro one](https://github.com/Robbe-B/maestro_mcz/assets/148912483/6f04a9de-f833-4e63-aad3-f53511591a49)

**Comment by Robbe-B** [comment]
Jmigueloliveira, I will need the diagnostics file of your stove.

Kind regards,
Robbe

Sent from Outlook for Android<https://aka.ms/AAb9ysg>

________________________________

**Comment by Robbe-B** [comment]
@jmigueloliveira, 
Is this solved for your hydro model aswell ? 
Since I don't have the diagnostics file, I can't really tell.
You can find the file here =>  "Settings" => "Devices & Services" => "Maestro MCZ" => "Go to your stove" => "Download diagnostics"
If you like the work we do, consider leaving a star on this github repo.
Thanks !
Kind regards,
Robbe

**Comment by Robbe-B** [comment]
> That's exactly what doesn't seem to work. Maybe the polling time is triggered differently on the older stoves?

@Voidfloop, this might sounds weird but can you send me a CSV export of your Transport Screw Speed ? 
With this I might be able to see if this is really not updating at the interval it should.
![image](https://github.com/Robbe-B/maestro_mcz/assets/103053873/caeefc8b-03ae-4902-9aaf-6ff797f8ef90)
![image](https://github.com/Robbe-B/maestro_mcz/assets/103053873/5bf27eb6-3d86-493a-80e6-a62aac4a5629)

Also you don't have anything in your logging ? 

Kind regards,
Robbe

**Comment by Voidfloop** [comment]
You can see that the data remains very static over a longer period of time.

[history_Wonzimmer_01.02.24-22.02.24 .csv](https://github.com/Robbe-B/maestro_mcz/files/14383495/history_Wonzimmer_01.02.24-22.02.24.csv)
[history_Wohnzimmer_today.csv](https://github.com/Robbe-B/maestro_mcz/files/14383496/history_Wohnzimmer_today.csv)

**Comment by Robbe-B** [comment]
@Voidfloop,
The changes are always when you are sending a set to the stove then ? 
Daimn, I wasn't aware this is not working for olders models 😞 
May split this off in another issue.

Kind regards,
Robbe

**Comment by Voidfloop** [comment]
New issue is created…
