### ISSUE TITLE
MCZ cloud down?

### ISSUE THREAD

**Issue by phil239** [Robbe-B/maestro_mcz#140]
**Describe the bug**
Since two days I can‘t control my stove (MUSA HYDROMATIC 18 M2) anymore in HA. The integration doesn’t receive any data. A login via the Maestro+ app is also not possible (I always get the error message „Oops, something went wrong“). 

I experienced those down times in the past, but never such a long one.

**Expected behavior**

**Screenshots**

**Diagnostics File**
While the bug is present, download the diagnostics file and attach it to this report.

**Comment by Robbe-B** [comment]
I have the same, there cloud is indeed down. This happens many times.
Kind regards,
Robbe

**Comment by Robbe-B** [comment]
@phil239, 
MCZ could is back up and running.
Conclusion: they even don't have a watchdog timer to restart crashed scripts, it's very sad. 
Resulting in an entire weekend downtime.
