### ISSUE TITLE
Can't turn on/off the stove

### ISSUE THREAD

**Issue by aertw** [Robbe-B/maestro_mcz#154]
I installed the integration and have different sensors working. I don't have a way to turn on or off the stove. This shows up in the log and might be related:

![image](https://github.com/user-attachments/assets/afe11005-b39e-41fc-884a-f271b74c5a51)

This error originated from a custom integration.

Logger: custom_components.maestro_mcz.maestro.responses.status
Source: custom_components/maestro_mcz/maestro/responses/status.py:265
integration: Maestro MCZ (documentation, issues)
First occurred: 10:35:17 (1722 occurrences)
Last logged: 12:58:16

Unknown status property 'vs_remoto' received from API endpoint. If this happens, please make an issue on the github repository
Unknown status property 'vs_wifi_home' received from API endpoint. If this happens, please make an issue on the github repository
Unknown status property 'sm_vs_bootloader' received from API endpoint. If this happens, please make an issue on the github repository
Unknown status property 'vs_ambient' received from API endpoint. If this happens, please make an issue on the github repository
Unknown status property 'sondaWifi' received from API endpoint. If this happens, please make an issue on the github repository

**Comment by Robbe-B** [comment]
Hi @aertw,

Can you provide me with the diagnostics file please ?

With that I'll be able to reproduce the issue.

Kind regards,

Robbe

**Comment by aertw** [comment]
Here is the diagnostics: [config_entry-maestro_mcz-01J7KNJ024QYZCF5MERNT1V9EQ.json](https://github.com/user-attachments/files/17026051/config_entry-maestro_mcz-01J7KNJ024QYZCF5MERNT1V9EQ.json)

I can't seem to find how to trigger on/off, even using dev tools/actions there doesn't seem to be an available action for the stove

It would be nice to use the on/off button in HA to avoid the crappy vendor software

**Comment by Robbe-B** [comment]
@aertw, 
At first sight I see you are using a very early version of this integration.
Would it be possible to upgrade to the current release first, since many, many, .... fixes happend during these versions.
![image](https://github.com/user-attachments/assets/d870dc2f-9b8d-45fe-aaa3-6346a98720d3)
Kind regards, 
Robbe

**Comment by aertw** [comment]
Thanks for the feedback! Although it seems strange that I installed it while searching for MCZ in the integrations tab. I will see if I can find a more recent version. Thanks again!

**Comment by aertw** [comment]
It works now... Thank you for assisting. Sometimes the obvious things are overlooked!

**Comment by Robbe-B** [comment]
@aertw, 
No problem, it happens from time to time, don't worry about it.
BTW, If you like the work we do, don't forget to give this repo a star !

Kind regards,

Robbe
