### ISSUE TITLE
MCZ Maestro Intergration for M1 Device

### ISSUE THREAD

**Issue by Hotzi57** [Robbe-B/maestro_mcz#161]
I use an MCZ ClubAir-10-M1 stove, which is not yet compatible with the MAESTRO Plus app. Is it possible to connect it to HA? After all, I also operate it with my smartphone or a Maestro remote control.

**Comment by Robbe-B** [comment]
@Hotzi57, 
This integration only supports cloud connected models, "MAESTRO +" in other words.
This naming is really confusing in my opinion. 
But for your model, there is another integration that should work.
See => https://github.com/Chibald/maestrogateway

**Comment by Robbe-B** [comment]
@Hotzi57,
You can use the "Maestro Upgrade" app to link your stove to the cloud, even if it's an M1 model. 
I recently did it myself for a "MCZ TILDA Comfort Air M1 10 kW"
Once you created a new cloud account and scanned the QR code of your stove, you should be able to add it via this integration in HA.
Kind regards,
Robbe

**Comment by Hotzi57** [comment]
Thank you, ITS great! The Upgrade App ist working.
But whats ist the "Username" and Passwort? WHO can i found IT?

Robbe-B ***@***.***> schrieb am Di., 26. Nov. 2024, 08:31:

**Comment by Robbe-B** [comment]
@Hotzi57, 
Step 1. You should create a new account yourself. (With the upgrade app on your phone)
Step 2. Scan the QR code of the stove and make sure it's linked to your cloud account. (With the upgrade app on your phone)
Step 3. Now add this Integration to you Home Assistant (Use the credentials you've created in step 1 )

**Comment by Robbe-B** [comment]
@Hotzi57,
It's the same account used for the app basically. 

Also, if you like the work we do, consider leaving a star ⭐ on this repository.

Kind Regards,
Robbe

**Comment by Hotzi57** [comment]
Yeah! It' s working! Thank you!

**Comment by Robbe-B** [comment]
@Hotzi57,
Great to hear ! 
If you like the work we do, consider leaving a star ⭐ on this repository.

Kind Regards,
Robbe
