### ISSUE TITLE
Add expected temperature sensor entity

### ISSUE THREAD

**Issue by asyd** [Robbe-B/maestro_mcz#168]
**Describe the solution you'd like**

I would like to have the expected temperature in HA. My goal is to have a dashboard with current temperature and expected one

Thanks @Robbe-B!

**Comment by asyd** [comment]
Thanks! Sorry for the inconvenience, first time I had a climate entity

**Comment by Robbe-B** [comment]
@asyd, 
No problem 😄 

If you like the work we do, consider leaving a star ⭐ on this repository.
Kind Regards,
Robbe
