### ISSUE TITLE
Stove toggles instead of taking the actual state into account (HVAC off/on)

### ISSUE THREAD

**Issue by RickType** [Robbe-B/maestro_mcz#54]
**Desired behaviour:** Stove is "ignoring" a state change via HA, if it's already in this state. E.g. when the stove is off and a "HVAC off" state is recieved, the stove will remain in off state.
**Actuall behaviour** is that the stove toggles. In off state a HVAC off will trigger the stove to switch to heat mode and vice versa.

**Comment by Robbe-B** [comment]
Will implement a workaround for this problem into the integration asap.
