### ISSUE TITLE
No Controls

### ISSUE THREAD

**Issue by Voidfloop** [Robbe-B/maestro_mcz#61]
Hello guys,
I only see the sensors and diagnostics on my two pellet stoves (EGO Air 10 Up and EGO Air 8. Unfortunately there are no controls.

![IMG_6910](https://github.com/Robbe-B/maestro_mcz/assets/146527945/4cf06309-2acb-47ce-b494-aba809e6cc88)

**Comment by Robbe-B** [comment]
Hi @Voidfloop,
Can you attach the diagnostics files for both stoves ?
I'll have a look what is going wrong here.
Thanks !

**Comment by Voidfloop** [comment]
Hi, thanks for the fast reply. sorry for the stupid question but where can I find the diagnostic files?

**Comment by Voidfloop** [comment]
Now I've found what I'm looking for

[MCZ EGO 8 config_entry-maestro_mcz-3f3bf13e5a79eac7ad71a45e245748ea.json.txt](https://github.com/Robbe-B/maestro_mcz/files/12780660/MCZ.EGO.8.config_entry-maestro_mcz-3f3bf13e5a79eac7ad71a45e245748ea.json.txt)
[MCZ EGO Comfort Air UP 10 config_entry-maestro_mcz-3f3bf13e5a79eac7ad71a45e245748ea.json.txt](https://github.com/Robbe-B/maestro_mcz/files/12780661/MCZ.EGO.Comfort.Air.UP.10.config_entry-maestro_mcz-3f3bf13e5a79eac7ad71a45e245748ea.json.txt)

**Comment by Robbe-B** [comment]
I'll have to investigate and I'll come back to you as soon as I have more information ! 
Thanks for the files !

**Comment by Robbe-B** [comment]
@Voidfloop,
I believe you are the first one to use this integration in combination with a M1+ stove (others are M2+)
This seems to have entire other configuration names.
I'm building support for it. 
Since I can't test this myself (don't have a M1+ stove).
I would like it if you can test out the different functionalities and verify these are actually working. (Keep in mind the 30sec polling time) 
I'll push this code within a couple of days probably.
Kind regards,
Robbe

**Comment by Voidfloop** [comment]
yes, MCZ ended support for the old app and dropped a new app via their cloud. I was really happy that my oven could finally work with Home Assistant. If you succeed, hundreds of users will be happy once the news has spread. I will of course test everything, thank you

**Comment by Robbe-B** [comment]
I can already give you a sneak peak of what it will look like for you :) (still work in progress)
![image](https://github.com/Robbe-B/maestro_mcz/assets/103053873/bb5bd167-bd01-40ae-8553-89526437d13b)

**Comment by Robbe-B** [comment]
@Voidfloop, 
You can try this out by installing [v0.4.0-beta](https://github.com/Robbe-B/maestro_mcz/releases/tag/v0.4.0-beta)
Let me know what is working and what not 😄 
Cheers !

**Comment by Robbe-B** [comment]
@Voidfloop,
Can you also provide me with a new screenshot + diagnostics file when the stove is actually switched on ? 
Thanks in advance,
Robbe

**Comment by Voidfloop** [comment]
I tested everything with my little model. The large stove has just been serviced and is still missing a seal. The manual control for the fan is missing. The fan also cannot be switched off with the button. The control between automatic and manual doesn't work either. (This doesn’t always work via the MCZ app either). I took a screenshot of the app for the fan control for you. I also noticed that the controls no longer work in the dashboard after a while. So turning it on works, but at some point I can no longer turn it off. Maybe just a temporary bug.

Thank you in advance for your work. You've come a long way, great

![IMG_6945](https://github.com/Robbe-B/maestro_mcz/assets/146527945/864ea2c3-df2e-48bc-b822-b983329d8a6f)
![IMG_6946](https://github.com/Robbe-B/maestro_mcz/assets/146527945/9ed1bdc1-0837-4127-9cc6-bac753a45277)
![IMG_6947](https://github.com/Robbe-B/maestro_mcz/assets/146527945/dd7d53d6-e971-4df9-a418-ae53be4b4643)
![IMG_6944](https://github.com/Robbe-B/maestro_mcz/assets/146527945/990aee02-f8d0-4873-83c2-ae1e27a89f63)

**Comment by Voidfloop** [comment]
[MCZ EGO 8 05.10.23 config_entry-maestro_mcz-adce20763d0d6ee095bf28563a0834a8.json.txt](https://github.com/Robbe-B/maestro_mcz/files/12819153/MCZ.EGO.8.05.10.23.config_entry-maestro_mcz-adce20763d0d6ee095bf28563a0834a8.json.txt)

**Comment by Robbe-B** [comment]
I'll look into these problems, you are aware of the 30 sec polling time right ? 
At most it can take 30sec to find your actions taking place. 
That can maybe explain some behavior ?

**Comment by Robbe-B** [comment]
I'm also very interested in the stove state, reported in the logbook.
Example of the states of my stove doing a 'full-cycle'
![image](https://github.com/Robbe-B/maestro_mcz/assets/103053873/5d71377b-086b-4b9b-b003-2bc6ec76a5b9)

**Comment by Voidfloop** [comment]
I put my big stove back into operation today.
Here the same. After the stabilization phase it gets the “off” signal and I no longer have control. But it continues to run normally.

![Screenshot 2023-10-06 at 15-31-28 Einstellungen – Home Assistant](https://github.com/Robbe-B/maestro_mcz/assets/146527945/d4f8b7f0-b7cb-4488-8e14-61da8972ab76)
![Screenshot 2023-10-06 at 15-33-03 Einstellungen – Home Assistant](https://github.com/Robbe-B/maestro_mcz/assets/146527945/dc78b035-b19c-4336-b0c4-f9823fe6d0a9)
[MCZ EGO Comfort AIR 10   06.10.2023 config_entry-maestro_mcz-adce20763d0d6ee095bf28563a0834a8.json.txt](https://github.com/Robbe-B/maestro_mcz/files/12831637/MCZ.EGO.Comfort.AIR.10.06.10.2023.config_entry-maestro_mcz-adce20763d0d6ee095bf28563a0834a8.json.txt)
