### ISSUE TITLE
2 Stoves appears since last major HA upgrade

### ISSUE THREAD

**Issue by RickType** [Robbe-B/maestro_mcz#65]
Since thr last HA update there are some issues with the connectivity.
The stove that has been added first have become unavailable and a new stove has been added which is reachable.
Diagnostics and Screenshot attached. This is not a one time correction. I corrected already twice. So it seems that this is a reoccuring defect.
<img width="1026" alt="Bildschirmfoto 2023-10-04 um 08 45 38" src="https://github.com/Robbe-B/maestro_mcz/assets/132100934/b1cd80cb-fa82-4ed9-9dd0-942cfad6c3b9">

[config_entry-maestro_mcz-c00135734c79e678be66179e3817369c.json.txt](https://github.com/Robbe-B/maestro_mcz/files/12800221/config_entry-maestro_mcz-c00135734c79e678be66179e3817369c.json.txt)

**Comment by Robbe-B** [comment]
Hmmmm, I can see that for whatever reason, the MCZ server API is returning an empty string for t he serial number of your stove 
![image](https://github.com/Robbe-B/maestro_mcz/assets/103053873/ea5d4729-d25a-4f33-ac6d-f752692f6e44)

**Comment by Robbe-B** [comment]
Is also see the the stove is currently not connected ? 
![image](https://github.com/Robbe-B/maestro_mcz/assets/103053873/5833dd1c-534c-4492-8b92-5dd89f643c16)
It might have something to do with that. 
I'll test this on my own stove.

**Comment by RickType** [comment]
Yes, stove was connected since the beginning. Unfortunately I can't reach the stove via the Maestro App either.... but I'm currently on holiday and can access the stove. But the disconnects seems to be also more often...

**Comment by Robbe-B** [comment]
Ok, as part of this issue, I'll look into a fix for not adding a second stove with an empty serial number when it's disconnected.

**Comment by Robbe-B** [comment]
@RickType, 
Do still have bluetooth disabled ? 
Good WiFi connection where the stove is located ? 
Recent Firmware update ? 
Can you provide me your Firmware numbers ? 
Thanks in advance,
Robbe

**Comment by RickType** [comment]
Hi,

the service technician might have enabled bluetooth again, two weeks ago. I need to check it. No firmware update during the last year. Wifi coverage is excellent.
Firmware version will be provided on Sunday, as I'm currently on holiday.

Rgds
Rick

**Comment by RickType** [comment]
Here u are:
![Bildschirmfoto 2023-10-08 um 16 04 05](https://github.com/Robbe-B/maestro_mcz/assets/132100934/87903635-a45d-4c9a-9545-4ddfbf977a9e)

**Comment by Robbe-B** [comment]
The BT on my stove is disabled and the polling interval is set to 30sec (the default).
So far I'm not experiencing any issue. 
Firmware: M2S.AIR.7.4, Panel:5, DB:SC12

**Comment by VaillantHassIo** [comment]
I've the same issue, not sure if it was HA Upgrade or the Integration update. Let me know if you need diagnosis data

**Comment by Robbe-B** [comment]
@VaillantHassIo,
Can you add the diagnostics file of the randomly added 2nd stove ?

**Comment by Leon3310** [comment]
Hello,

I've had the same issue for some time.

![image](https://github.com/Robbe-B/maestro_mcz/assets/109483356/a3e3b45e-5517-4af5-bca9-d3750c40668a)

![image](https://github.com/Robbe-B/maestro_mcz/assets/109483356/aac7859a-b2cd-41e5-9225-90622bb862ba)

[config_entry-maestro_mcz-6f1c0247608bfa5e0d7916195467a787.json(2).txt](https://github.com/Robbe-B/maestro_mcz/files/13046313/config_entry-maestro_mcz-6f1c0247608bfa5e0d7916195467a787.json.2.txt)

**Comment by Robbe-B** [comment]
This should be fixed in [v0.4.2-beta](https://github.com/Robbe-B/maestro_mcz/releases/tag/v0.4.2-beta)

**Comment by Robbe-B** [comment]
You might have to delete your current integration and re-add it, to get rid of the duplicate stoves.

**Comment by RickType** [comment]
Hi Robbe,

thanks again for the bugfix.
Just a heads up I faced now two times the issue that a automation triggered the stove to switch on/off, but nothing happened. I removed and re-added the stove now to check if this is fixing the issue.
Don't know if this is related to the latest fix. Will open a new defect if this will happen again.

Thx
Rick

**Comment by Robbe-B** [comment]
> Just a heads up I faced now two times the issue that a automation triggered the stove to switch on/off, but nothing happened.

I had the same with my stove, but when debugging, I've noticed the integration was really sending the command to the cloud.
Conclusion, this was a backend issue, they are really messing things up at the backend side lately.
I even had this exact same behavior this the android app.
Anyway, since the last backend down time, this issue seems to be fixed for now 🤞

**Comment by RickType** [comment]
Yes, the backend and the internet page was down for nearly two days. Addtionally I had the issue that the stove was in a restarting loop. Now they fixed it. In the meanwhile I also reconfigured the system, as I want to be independed from the MCZ cloud. Currently I'm running the system configuration 5, which is usually intended to be used with an external thermostat. In my case I use a shelly that closes the contact when the stove needs to be switched on. For this I do not need any MCZ backend. I need a certain reliability, as I use the stove as  the main heat source.

**Comment by Robbe-B** [comment]
For me it's just a pitty that MCZ always tries to 'hide' and 'lock down' every connection with the stove, in the end we still payed 8K for it right ? So my stove, my control, you would think, right ?

One day, I would love to include local control via bluetooth in this integration aswell. 
But since they are using a proprietary protocol, we don't have a clue on how to use it.

**Comment by RickType** [comment]
Hi Robbe, I agree, there should be an API that should be well documented.
I think the majority of the people uses the MCZ steering, or just installing a thermostat that trigger the stove.
I believe that are 99% of all customers. Therefore MCZ ist not interested to fix it in the near future.
At least I managed it know to become a litlle bit more independend, as I use a shelly to imitate a thermostat. So if the MCZ backend is not working, the stove will still switch on. The buffer temp comes from a shelly plus add on. The shelly integration works very reliable with HA, which is somehow required for a heating system. Therefore I'll stay with this solution. No, it is not that fancy and has some restrictions, but it works reliable. What stays important is that I can see if the stove is switched on. There is a routine that checks if the stove has been switched on. If not, the gas heater kicks in. So I appreaciate your work and committment and hope that this will continue in the future. But you always are one step behind MCZ, as the interface is not standardized. Don't know if there is any manufacturer that offers a "good" and reliable interface?
