### ISSUE TITLE
Fan Speed configuration missing when only 1 Fan is available

### ISSUE THREAD

**Issue by VaillantHassIo** [Robbe-B/maestro_mcz#72]
Not sure when this has changed but i can't find the optuion to change the fan speed

![grafik](https://github.com/Robbe-B/maestro_mcz/assets/87522613/d43b693c-8a32-4898-b851-d64c41b2741d)

**Comment by VaillantHassIo** [comment]
[config_entry-maestro_mcz-466d8e4de749e610e22c8bce7783edad.json(3).txt](https://github.com/Robbe-B/maestro_mcz/files/12917090/config_entry-maestro_mcz-466d8e4de749e610e22c8bce7783edad.json.3.txt)

**Comment by Robbe-B** [comment]
MCZ changed the config for FAN 1, I've also noticed this some time ago. I'll look into fixing this.

**Comment by Leon3310** [comment]
Hello,
I have the same problem with my stove which has two fans.
Only the second fan is visible in home assistant.

Thanks 

![image](https://github.com/Robbe-B/maestro_mcz/assets/109483356/6244ffad-89bc-46c2-b316-b747554e3f19)


[config_entry-maestro_mcz-df57f039dff96c4ad058338ada8306e3.json.txt](https://github.com/Robbe-B/maestro_mcz/files/13823657/config_entry-maestro_mcz-df57f039dff96c4ad058338ada8306e3.json.txt)

**Comment by Robbe-B** [comment]
UPDATE: I'm currently working on a fix, it's already working for my model, but I need some testers for the M1+ models as well. 
This is harder than I initially thought since the fan configurations are now embedded in the configuration of the current mode the stove is in. This means I had to make a mapping foreach mode to the right configuration. I did this foreach mode I know of, but hopefully this will be the same for other models. That's actually the hardest part, I can't test on other models (e.g. hydro, ...).

**Comment by VaillantHassIo** [comment]
happy to do some beta-testing

**Comment by Robbe-B** [comment]
@VaillantHassIo, I'll soon post a PR linked to this item.

**Comment by lalek54** [comment]
Happy to do some beta testing to. 👍
Is it solving the other problem with fan? 
![IMG_7137](https://github.com/Robbe-B/maestro_mcz/assets/35529735/5b6530fd-cdcf-46f8-82d2-f36b62e41493)

**Comment by lalek54** [comment]
here is the log:

`Logger: homeassistant.components.websocket_api.http.connection
Source: components/websocket_api/commands.py:238
Integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 13:35:52 (5 occurrences)
Last logged: 20:27:10

[547504673856] MczFanEntity.async_turn_on() takes 1 positional argument but 3 were given
[547604844352] MczFanEntity.async_turn_on() takes 1 positional argument but 3 were given
[547506757056] MczFanEntity.async_turn_on() takes 1 positional argument but 3 were given
[547641341504] MczFanEntity.async_turn_on() takes 1 positional argument but 3 were given
[547507256384] MczFanEntity.async_turn_on() takes 1 positional argument but 3 were given
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 238, in handle_call_service
    response = await hass.services.async_call(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2149, in async_call
    response_data = await coro
                    ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2186, in _execute_service
    return await target(service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 272, in handle_service
    return await service.entity_service_call(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 882, in entity_service_call
    single_response = await _handle_entity_call(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 952, in _handle_entity_call
    result = await task
             ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/fan/__init__.py", line 334, in async_handle_turn_on_service
    await self.async_turn_on(percentage, preset_mode, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: MczFanEntity.async_turn_on() takes 1 positional argument but 3 were given
`

**Comment by lalek54** [comment]
and the diagnostics files: 
[config_entry-maestro_mcz-04a794c9c7eed4e9f7e8ecaf83460238.json.txt](https://github.com/Robbe-B/maestro_mcz/files/13907548/config_entry-maestro_mcz-04a794c9c7eed4e9f7e8ecaf83460238.json.txt)

**Comment by lalek54** [comment]
and of course I give you a star. You did a great job with this integration.
Thanks a lot.

**Comment by Robbe-B** [comment]
@VaillantHassIo, @Leon3310, @lalek54, 

You guys can start BETA testing with this change.
Official release will follow after testing.
Meanwhile, I'll keep making improvements on this.

Cheers, 
Robbe

**Comment by VaillantHassIo** [comment]
Great! HACS doesnt seem to find an updated beta version. Do you want us to load the code directly or did you release a new beta?

**Comment by Robbe-B** [comment]
@VaillantHassIo , I can release a new pre-release if you want ?

**Comment by Robbe-B** [comment]
Update: pre-release [v0.4.4-beta](https://github.com/Robbe-B/maestro_mcz/releases/tag/v0.4.4-beta) is now available !

**Comment by VaillantHassIo** [comment]
Great work!

<img width="435" alt="image" src="https://github.com/Robbe-B/maestro_mcz/assets/87522613/f49cb383-492d-45aa-b292-75b20de4c0c0">

**Comment by lalek54** [comment]
Wow quick update. Thanks a lot. 
seems a lot better: fan 1 came back, I was able to change fan 3 mode to silent. 
but now I me unable to command fans. 
nothing happen et still the same error. 
![IMG_7141](https://github.com/Robbe-B/maestro_mcz/assets/35529735/0611e337-c68d-49c9-9c50-46ad3c25c549)
![IMG_7140](https://github.com/Robbe-B/maestro_mcz/assets/35529735/326d97ca-3c0d-4d61-a039-a2f13bea0f6d)

**Comment by lalek54** [comment]
Wow. Crazy fast answer. Thanks. It s working except an error message but that’s fine.  
i can’t set « auto » mode because it s not defined as preset mode. 
am I able able to add it somewhere tonuse it? 
![IMG_7143](https://github.com/Robbe-B/maestro_mcz/assets/35529735/4b7c5fe3-7f7c-47d0-a0ae-ad77cda5067b)
