### ISSUE TITLE
V 0.4.2 Beta stove loses integrity (M1+)

### ISSUE THREAD

**Issue by Voidfloop** [Robbe-B/maestro_mcz#75]
With the V 0.4.2 beta I only see one of my two stoves. Going back to the V0.4.1 beta doesn't show the phenomenon. I use two M1+ models. Have you made any progress with the problem that the stove can no longer be controlled with your integration after the stabilization phase?

**Comment by Robbe-B** [comment]
@Voidfloop,
I would think this is by design, are both stoves plugged in and connected ? 
In v0.4.2 a change was made in order to not show disconnected devices anymore since these are uncontrollable anyway.
Can you maybe remove the integration and re-add it while both stoves are connected ? 
Let me know if you still have trouble.
Kind regards,
Robbe

**Comment by Voidfloop** [comment]
I just switched back to the v 0.4.2 beta and no entities are available from a Stove anymore. Back to v 0.4.1 and the Stove is back.
I tried everything else... unfortunately the result is that it must be due to v 0.4.2.

**Comment by Robbe-B** [comment]
Can you give me your diagnostics file from v0.4.1 ? 
I'm almost certain these stoves are simply not connected to the cloud at that point.
Or Maybe they handled that differently for M1+ models 😞

**Comment by Voidfloop** [comment]
[Downgrade v 0.4.1 config_entry-maestro_mcz-a53929bdd1e2e92feb77692934fea185.json.txt](https://github.com/Robbe-B/maestro_mcz/files/13169038/Downgrade.v.0.4.1.config_entry-maestro_mcz-a53929bdd1e2e92feb77692934fea185.json.txt)

**Comment by Voidfloop** [comment]
Everything deleted and the v 0.4.1 beta loaded and both stoves are recognized when accessing the cloud. Here are the diagnostics:

[v 0.4.1 config_entry-maestro_mcz-8a7a7d8ba44c6ad9eb0d2829c3805c16.json.txt](https://github.com/Robbe-B/maestro_mcz/files/13174471/v.0.4.1.config_entry-maestro_mcz-8a7a7d8ba44c6ad9eb0d2829c3805c16.json.txt)

**Comment by Voidfloop** [comment]
Everything deleted and the v 0.4.2 beta loaded and only one stove is recognized when accessing the cloud. Here are the diagnostics:
[v 0.4.2 config_entry-maestro_mcz-5cdd4834f9a3b64ad866ce33567dedc0.json.txt](https://github.com/Robbe-B/maestro_mcz/files/13174495/v.0.4.2.config_entry-maestro_mcz-5cdd4834f9a3b64ad866ce33567dedc0.json.txt)

**Comment by Voidfloop** [comment]
Both stoves are correctly registered in the cloud.
Already tried all possibilities. Reload HA, delete API and reload etcetera.

If you can get the problem under control, then we still have to look at the problem that the stoves can no longer be controlled after a while.
I will then open a new issue for this.
Thanks for your great work.

**Comment by Robbe-B** [comment]
@Voidfloop, 
Are you running the latest and greatest firmware of these stoves ?

**Comment by Voidfloop** [comment]
I don't think the firmware is up to date. Updates are reserved for the service technician. This is a disaster at MCZ. I would like to have an account for the MCZ Pro app to update My Stoves. The “basement” stove is actually 2 years younger than the “living room”.

**Comment by Robbe-B** [comment]
I believe you can update the firmware of your stove via the MCZ Maestro app.
Adjustments/Settings => Firmware Update => Board Firmware.

**Comment by Robbe-B** [comment]
@Voidfloop,
Better late then never 😄 
Can you test V0.4.3-beta ? 
Your feedback would be very valuable.
Kind Regards,
Robbe

**Comment by Voidfloop** [comment]
Hello and thank you for your work!
You're getting closer.
The stove can be switched on and after the stabilization phase it receives the feedback “Stove switched off” again.
But this time he continues to receive feedback from the stove and I can make settings. The stove emits a beep with every input.
But one thing, the Stove is in the "Off" state and can't turn it off.
<img width="243" alt="Stove_Off" src="https://github.com/Robbe-B/maestro_mcz/assets/146527945/8ee4aeb1-1989-4bba-9af8-7b088f116792">



[MCZ EGO 8 v 0.4.3Beta.json.txt](https://github.com/Robbe-B/maestro_mcz/files/13812744/MCZ.EGO.8.v.0.4.3Beta.json.txt)
