### ISSUE TITLE
Manage the eco mode

### ISSUE THREAD

**Issue by elzinc85600** [Robbe-B/maestro_mcz#77]
Hello
first thing, thanks to much for the current staff done at this day.
I didn't find how to enable the stove with the eco mode enable.
is it in the todo list ? (or already in place, and sorry in this case, but could you describe "howto" please).

Thanks
Francois

**Comment by Robbe-B** [comment]
Hi @elzinc85600,
Thanks for asking this question. 
Can you maybe share a screenshot of what you are seeing ?
And adding your diagnostics file would be great aswell ! 
![image](https://github.com/Robbe-B/maestro_mcz/assets/103053873/4fd4a847-037b-428c-9d26-a5267223f69e)
Kind regards,
Robbe

**Comment by elzinc85600** [comment]
Hello Robbe,
in attachment 2 files (one with eco mode enabled from MCZ app, and the other one without).
I found a diff at the variable : "att_eco"
But i don't know how this setting is represented on HomeAssistant ; or how to be able to used it. In HA "dev tool", i don't found any "eco" setting when filtering on "MCZ" entries.
My need is to replace the MCZ app, and so be able to start stove based on a calendar, and also managed the eco mode :)

last point, it seems that when the stove is in auto mode (timer + eco), the thermosta entry show "mode:Off". When i disable the timer mode, and powerOn the stove, thermosta entry is correctly updated.

[config_entry-maestro_mcz-ecoDisabled.json.txt](https://github.com/Robbe-B/maestro_mcz/files/13304957/config_entry-maestro_mcz-ecoDisabled.json.txt)
[config_entry-maestro_mcz-ecoEnabled.json.txt](https://github.com/Robbe-B/maestro_mcz/files/13304958/config_entry-maestro_mcz-ecoEnabled.json.txt)

Thanks.
Regards

**Comment by Robbe-B** [comment]
I think there is just a different naming here "ECO" is called "Start / Stop" isn't it ? 
![image](https://github.com/Robbe-B/maestro_mcz/assets/103053873/aece7f5a-ea60-400c-96dd-910f5e215f67)

**Comment by elzinc85600** [comment]
> I think there is just a different naming here "ECO" is called "Start / Stop" isn't it ? ![image](https://user-images.githubusercontent.com/103053873/281651361-aece7f5a-ea60-400c-96dd-910f5e215f67.png)

i'm so stupid, you're right !
i've done the test disabling the eco mode in MCZ app, and indeed it updates this entry in HA.

**Comment by Robbe-B** [comment]
Anyway, thanks for your information and config file, the more models I have in my collection of config files, the more testing I can perform when pushing a change.

Kind regards, 
Robbe

**Comment by elzinc85600** [comment]
sure. and again, thanks a lot for this integration :)
