### ISSUE TITLE
Beeps on the stove

### ISSUE THREAD

**Issue by xvisionbelgium** [Robbe-B/maestro_mcz#78]
HI
Just tested this integration. It works nice but has an annoying side effect on my stove (MCZ Maestro)
On every refresh (by default this seems to be 30sec) of the data the stove beeps a couple of times, meaning that a value of a parameter is set on the stove.
Why are parameters set if there was no change on the values ?

**Comment by Robbe-B** [comment]
@xvisionbelgium,
Any update on this ?

**Comment by Robbe-B** [comment]
Anyone having the same problem as @xvisionbelgium  ?

**Comment by xvisionbelgium** [comment]
For the moment I disabled the beep with the MCZ app.... but as soon as I enable the setting in the app again we got them back on every refresh from HA

**Comment by Robbe-B** [comment]
@xvisionbelgium 
Can you add the diagnostics file that you can download from the integration ?  
With that I'll be able to continue the investigation.
Thanks !
Robbe

**Comment by xvisionbelgium** [comment]
[config_entry-maestro_mcz-f78ac6b460b4d6763969b38fc9e7b4a0.json.txt](https://github.com/Robbe-B/maestro_mcz/files/13885306/config_entry-maestro_mcz-f78ac6b460b4d6763969b38fc9e7b4a0.json.txt)
 As Requested

**Comment by Robbe-B** [comment]
@xvisionbelgium, 
Can you check if you still have the same problem [v0.5.3-beta](https://github.com/Robbe-B/maestro_mcz/releases/tag/v0.5.3-beta) ? 
Kind regards, 
Robbe

**Comment by xvisionbelgium** [comment]
Hi Robbe,
Just updated, enabled the beep setting again and now it only beeps when there is an actual setting change.

Great fix !

Verzonden vanuit Outlook voor iOS<https://aka.ms/o0ukef>
________________________________
Van: Robbe-B ***@***.***>
Verzonden: Saturday, February 17, 2024 9:21:19 AM
Aan: Robbe-B/maestro_mcz ***@***.***>
CC: Johan Hamelinck (XV) ***@***.***>; Mention ***@***.***>
Onderwerp: Re: [Robbe-B/maestro_mcz] Beeps on the stove (Issue #78)

You don't often get email from ***@***.*** Learn why this is important<https://aka.ms/LearnAboutSenderIdentification>

@xvisionbelgium<https://github.com/xvisionbelgium>,
Can you check if you still have the same problem v0.5.3-beta<https://github.com/Robbe-B/maestro_mcz/releases/tag/v0.5.3-beta> ?
Kind regards,
Robbe

**Comment by Robbe-B** [comment]
@xvisionbelgium, 
Great to hear the fixes are sufficient ! 
If you like the work we do, consider leaving a star on this repo.
Thanks !

Kind regards,
Robbe
