### ISSUE TITLE
the Climate entity's status changes to off

### ISSUE THREAD

**Issue by HomeAssistantCed** [Robbe-B/maestro_mcz#79]
Hello,

I recently switched to this integration instead of gateway + mqtt.
Everything works perfectly except the climate entity in home assistant.
Once turned on (via ha), the status becomes off after 10 minutes.
If I turn on the stove manually or via the app, the climate entity remains in off mode.

[config_entry-maestro_mcz-7c782516d871c69367975910938dbc28.json (1).txt](https://github.com/Robbe-B/maestro_mcz/files/13470031/config_entry-maestro_mcz-7c782516d871c69367975910938dbc28.json.1.txt)

Thank you.

![image](https://github.com/Robbe-B/maestro_mcz/assets/84478966/9c560f07-628a-486f-bc40-b04f61b4dc44)

**Comment by Crisicus** [comment]
@HomeAssistantCed 
I'm curious to know what you mean by gateway + mqtt.
Could you elaborate further on that?

**Comment by HomeAssistantCed** [comment]
I use the Mcz Maestro Gateway add-on.
With a yaml file that maps my mqtt to an entity .

https://github.com/SebLz/ha-addons/tree/main/maestro_gateway

![image](https://github.com/Robbe-B/maestro_mcz/assets/84478966/56ae30ca-d2af-4fe5-96aa-f34cea54b2a6)

**Comment by Robbe-B** [comment]
@HomeAssistantCed, 
This diagnostics file, whas this downloaded while the stove was on ? 
Kind Regards,
Robbe

**Comment by leutnantlurch** [comment]
Hey guys, I have the same issue, i can turn the stove on but the "switch" in HA switches to off. The only possible way to turn of the stove is to turn it off via the app oder at the device itself.

What do you need for troubleshooting?

**Comment by Robbe-B** [comment]
@leutnantlurch,
Thanks for reporting this issue.
Can you share your stove diagnostics file form your stove when it's on and also when it's off ? 
Kind regards,
Robbe

**Comment by leutnantlurch** [comment]
@Robbe-B Thank you your response and sorry for my late response, I was pretty busy :( 

Apologies for my knowledge but I found out, that I use a stove with "normal" Maestro, not the Mastero+ (the funny thing is, i can login and the integration shows valid values from my stove) but perhaps this is the problem for me? 

![image](https://github.com/Robbe-B/maestro_mcz/assets/129696204/e7cd0471-d7b9-4d18-8fe1-8da610f01056)
[config_entry-maestro_mcz-6fd5acdd6cde59f20fefeea208355bfe.json (1).txt](https://github.com/Robbe-B/maestro_mcz/files/14037073/config_entry-maestro_mcz-6fd5acdd6cde59f20fefeea208355bfe.json.1.txt)

I've attached the diagnostic file (stove off) in the evening or tomorrow I can send a file with stove on :)

**Comment by leutnantlurch** [comment]
I hope it is the correct file, this is the diagnostics while the stove was on:

[config_entry-maestro_mcz-6fd5acdd6cde59f20fefeea208355bfe.json.txt.json](https://github.com/Robbe-B/maestro_mcz/files/14038975/config_entry-maestro_mcz-6fd5acdd6cde59f20fefeea208355bfe.json.txt.json)

As for the symptoms, I can turn the stove on and for a while, the stove show as running but after a little while, the switch in HA goes to off (the stove continous to run).

**Comment by Robbe-B** [comment]
@HomeAssistantCed, @leutnantlurch, 
By installing [v0.5.3-beta](https://github.com/Robbe-B/maestro_mcz/releases/tag/v0.5.3-beta) you should be able to have this problem fixed :) 

Cheers, 
Robbe
