### ISSUE TITLE
Immidiate Feedback on ON/OFF

### ISSUE THREAD

**Issue by benjamishirley** [Robbe-B/maestro_mcz#81]
I am controlling the integration via physical KNX devices. It would be nice if it would be possible to receive immediate feedback when switching the stove on or off because this would allow for the state change to be send back to the KNX Bus to visualize the device has turned on or off correctly.

At the moment this can take up to 30 seconds waiting for a polling interval to complete. Would it not be possible to always poll the device state information shortly after an event (switching on or off) was initiated?

Benjamin

**Comment by Robbe-B** [comment]
Hi, @benjamishirley, 
I'm aware of this.
Unfortunately, this is not something we can resolve at the integration side.
Polling the cloud faster is not an option, since changes only reflect in the MCZ database after 30secs of time.
Even if we polled the cloud every second, the change should still only reflect after 30sec.

Kind Regards, 

Robbe

**Comment by Robbe-B** [comment]
The only workaround I can think of, is to put an "assumed state" in your automations, where you simply assume the action has taken place after command execution, after 30 sec you can then check if this was true.

**Comment by benjamishirley** [comment]
> The only workaround I can think of, is to put an "assumed state" in your automations, where you simply assume the action has taken place after command execution, after 30 sec you can then check if this was true.

I implemented something similar as a workaround right now. I tell my KNX devices to consider the button press as a temporary state that immediately reflects on the devices. 

Thanks for the hint, I wish nice holidays. 

Benjamin
