### ISSUE TITLE
Hydro Stove - 1 Fan von MCZ 

### ISSUE THREAD

**Issue by smarthome123456789** [Robbe-B/maestro_mcz#82]
Hallo, Ich erhalte seit einigen Tagen diese Fehlermeldung. Was hat dies zu bedeuten?

Dieser Fehler wurde von einer benutzerdefinierten Integration verursacht

Logger: custom_components.maestro_mcz.maestro.responses.status
Source: custom_components/maestro_mcz/maestro/responses/status.py:287
Integration: Maestro MCZ (documentation, issues)
First occurred: 18:49:04 (155 occurrences)
Last logged: 19:06:22

Unknown status property 'temp_max_stufa_off' received from API endpoint. If this happens, please make an issue on the github repository
Unknown status property 'temp_min_stufa_on' received from API endpoint. If this happens, please make an issue on the github repository
Unknown status property 'isConfigValid' received from API endpoint. If this happens, please make an issue on the github repository
Unknown status property 'ingr_flux' received from API endpoint. If this happens, please make an issue on the github repository
Unknown status property 'soglia_usc_temp' received from API endpoint. If this happens, please make an issue on the github repository

Vielen Dank

**Comment by Robbe-B** [comment]
Hi @smarthome123456789,
Thanks for flagging this problem, can you attach your diagnostics file from the integration aswell ? 

Kind Regards,

Robbe

**Comment by smarthome123456789** [comment]
Vielen Dank für die schnelle Rückmeldung. 

Die gewünschte Diagnosedatei im Anhang. ( Hoffe das passt so - ist meine erste Meldung, alles neu für mich )
[config_entry-maestro_mcz-8280ae8889064687d1961d0932ea828b.json (2).txt](https://github.com/Robbe-B/maestro_mcz/files/13772221/config_entry-maestro_mcz-8280ae8889064687d1961d0932ea828b.json.2.txt)


Mit freundlichen Grüßen 

Marco

**Comment by Robbe-B** [comment]
@smarthome123456789, 
Issue is addressed, thanks for reporting these log lines ! 

If you like the work we do, don't forget to drop us a star on this repo !

Kind Regards,
Robbe
