### ISSUE TITLE
Fan - v0.4.4-beta

### ISSUE THREAD

**Issue by Leon3310** [Robbe-B/maestro_mcz#91]
Hello,

Thanks for the update. Here are the results of the first tests.

The 2 fans on my stove are in home assistant.

However, in manual mode, when I change the power on fan 1 or 2. Nothing happens.

I think that in the previous version I was able to change the fan power on the 2nd fan.

I also have a question: What is the purpose of the switch on the fans? The switch is always ON

To configure the fans, perhaps you should also try to do something similar to the app.

There is a "Silent mode" mode (for all fans) - Bottom of the screen

There is a mode for each fan (Auto, No air (0) , 1->5)

These are small details compared to the work you've done.

Thank you very much

![Screenshot_2024-01-12-16-32-22-501_it mcz maestro](https://github.com/Robbe-B/maestro_mcz/assets/109483356/4fe098ba-f06f-496a-9d0e-efcf21c3b6bf)

![Capture d'écran 2024-01-12 163938](https://github.com/Robbe-B/maestro_mcz/assets/109483356/f37b4591-6751-4cdb-8a4d-05eb34cd919b)

![Capture d'écran 2024-01-12 164018](https://github.com/Robbe-B/maestro_mcz/assets/109483356/9e627dc4-15ea-42e2-bba1-8460d86bb2a6)

**Comment by Robbe-B** [comment]
@Leon3310, 
Can you check with [v0.4.6-beta](https://github.com/Robbe-B/maestro_mcz/releases/tag/v0.4.6-beta) if you are experiencing the same  ? 
Maybe attach the diagnostics file.

Kind regards, 
Robbe

**Comment by lalek54** [comment]
Sorry for my message in the other thread. 
0.4.6 is great. Incredible work and so fast. Thank you your job. 
![IMG_7144](https://github.com/Robbe-B/maestro_mcz/assets/35529735/a9f087cc-85a6-46e3-9542-cc7a0668398b)
 Manual mode is working as expected. Preset 0 seems to be no air mode. 
but I am unable to set auto mode. 
Seems to be defined as « auto » in the app and not with a number. 
![IMG_7143](https://github.com/Robbe-B/maestro_mcz/assets/35529735/05c8fd0a-7c86-44a8-8267-9028801db8ad)

**Comment by Leon3310** [comment]
Hello, 

It now works with the new version.

Thanks a lot

**Comment by Robbe-B** [comment]
@lalek54,
Will be fixed soon.

Kind regards,
Robbe

**Comment by lalek54** [comment]
Thank you so much. 
kind regards. 
Alex.

**Comment by Robbe-B** [comment]
@lalek54, 
Check out the structural changes of #93 
The speed / preset mechanism has changed.
Cheers,
Robbe

**Comment by lalek54** [comment]
Yes I saw it this morning. That's great now. When we ll be able to turn off silent mode this integration will be perfect. that s a lot of work. thank you again.
