### ISSUE TITLE
Add icon

### ISSUE THREAD

**Issue by Leon3310** [Robbe-B/maestro_mcz#95]
Hello,

We could also use these icons for "overnight" and "manual".

weather-night
hand-back-right-outline

Thank you

![image](https://github.com/Robbe-B/maestro_mcz/assets/109483356/a38f2199-ca0f-4414-b16a-1de7df4ab695)

**Comment by Robbe-B** [comment]
Hi, @Leon3310,
Currently, there is no way for us to set these icons from within the integration.
It's up to the HA logic itself to present you with a matching icon here.
However, I've watched the HA release party livestream, I believe they promised some improvements for this soon.
Maybe we will be able to override this icon in the future.

Kind regards,
Robbe

**Comment by Robbe-B** [comment]
Good news for this one. 

See => https://rc.home-assistant.io/blog/2024/01/31/release-20242/#icons-everywhere
