### ISSUE TITLE
Alarm Reset - does not clear on Button Press

### ISSUE THREAD

**Issue by VaillantHassIo** [Robbe-B/maestro_mcz#96]
**Describe the bug**
Service Clear Alarm doesnt work

**Expected behavior**
Nothing happens.

**Screenshots**
<img width="223" alt="image" src="https://github.com/Robbe-B/maestro_mcz/assets/87522613/2d6faf6c-e9ee-4b29-8bfd-1ca797172620">

**Diagnostics File**
attached to case
[config_entry-maestro_mcz-466d8e4de749e610e22c8bce7783edad.json.txt](https://github.com/Robbe-B/maestro_mcz/files/13937953/config_entry-maestro_mcz-466d8e4de749e610e22c8bce7783edad.json.txt)

**Comment by Robbe-B** [comment]
@VaillantHassIo,
A2 alarm isn't clearable remotely.

**Comment by Robbe-B** [comment]
FYI https://user-images.githubusercontent.com/103053873/235351600-71a8289b-a972-4cc0-a480-699c5b898303.jpg

**Comment by VaillantHassIo** [comment]
Thanks. That explains my situation.
